# Generated by Django 5.0 on 2023-12-21 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urls',
            name='redirect_to',
        ),
        migrations.AlterField(
            model_name='urls',
            name='base62_id',
            field=models.CharField(unique=True),
        ),
        migrations.AlterField(
            model_name='urls',
            name='long_url',
            field=models.URLField(unique=True),
        ),
    ]
