# Generated by Django 5.0 on 2023-12-21 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urls', '0004_alter_urls_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urls',
            name='base62_id',
            field=models.CharField(null=True, unique=True),
        ),
    ]
