name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:alpine
        ports:
          - "6379:6379"
      db:
        image: postgres:14.9
        ports:
          - 5432:5432
        command: postgres -D /var/lib/postgresql/data -F -c logging_collector=on
        volumes:
          - ./data/dev:/var/lib/postgresql/data
        healthcheck:
          test: ["CMD-SHELL", "pg_isready -U postgres"]
          interval: 10s
          timeout: 5s
          retries: 5
        environment:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: blue_coding
          POSTGRES_HOST: db
          PGDATA: /var/lib/postgresql/data
          LOGGING_COLLECTOR: 'on'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: |
          docker-compose up -d

      - name: Wait for services to be ready
        run: |
          until docker-compose exec -T server python manage.py check; do
            sleep 5
            echo "Retrying..."
          done

      - name: Run Django tests
        run: |
          docker-compose exec -T server python manage.py test apps/*

      - name: Tear down Docker Compose
        run: |
          docker-compose down
