name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: blue_coding_test
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: |
          sudo docker-compose -f docker-compose.yml up -d

      - name: Wait for services to be ready
        run: |
          until sudo docker-compose -f docker-compose.yml exec -T django_project_server python -c "import psycopg2; conn = psycopg2.connect('dbname=blue_coding_test user=user password=password host=db'); conn.close()"; do
            sleep 5
            echo "Retrying..."
          done

      - name: Run Django tests
        run: |
          sudo docker-compose -f docker-compose.yml exec -T your-django-container-name python manage.py test

      - name: Tear down Docker Compose
        run: |
          sudo docker-compose -f docker-compose.yml down
