name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up Docker Compose
        env:
          BASE_URL: 'https://example.com'
        run: |
          docker-compose up -d

      - name: Wait for services to be ready
        run: |
          until docker-compose exec -T server python manage.py check; do
            sleep 5
            echo "Retrying..."
          done

      - name: Run Django tests
        run: |
          docker-compose exec -T server python manage.py test apps/*

      - name: Tear down Docker Compose
        run: |
          docker-compose down
